### ISSUE TITLE
Red screen error when accessing wallet in RSK

### ISSUE THREAD

**Issue by alepc253** [MyCryptoHQ/MyCrypto#3933] opened 2021-04-14 20:34 UTC
### Description of Issue

Error unlocking wallet in RSK network

### What exactly were you doing when you encountered this issue?

1. Connect to RSK network
2. Access your wallet using hardware wallets, private key or mnemonics
3. Red screen

### How were you accessing your wallet?

It fails with every method (hardware wallets, private key and mnemonics)

### Description of Your Machine

- Operating system: MacOS
- MyCrypto Desktop Application v1.7.13
- MyCrypto Version Number:

### Console Logs / Screenshots

<img width="1228" alt="Screen Shot 2021-04-14 at 15 57 16" src="https://user-images.githubusercontent.com/3451282/114774875-0c53f600-9d47-11eb-9211-729d79540500.png">

**Comment by Mrtenz** [comment] 2021-04-14 20:48
Duplicate of #3890. The issue was fixed in #3900, which should be included in the next release. You can use app.mycrypto.com as a workaround.

Thanks for the report!

**Closed by Mrtenz** 2021-04-14 20:48 UTC
