### ISSUE TITLE
Send Transaction is greyed out

### ISSUE THREAD

**Issue by Varunram** [MyCryptoHQ/MyCrypto#1958] opened 2018-06-16 08:03 UTC
### Description of the Issue

When I try to send a transaction (via the Musicoin network), I'm a able to send to one address pretty fine. When I try to send to the second address, the "Send Transaction" button is greyed out and it lights up back agin only when I shift tabs and return back. I do have funds in the account, so I found it a bit weird. Only a minor inconvenience, but still :)

### Description of Your Machine

Safari 11 on macOS 10.13.3

**Comment by wbobeirne** [comment] 2018-06-17 04:46
This is unfortunately a known issue reported with #1910. The issue is the nonce doesn't refresh, and since that's a hidden field (behind advanced gas settings) users won't see a field highlighted as invalid. I think a fix is either in the works, or will be added with the next release.

Closing this to consolidate to a single issue.

**Closed by wbobeirne** 2018-06-17 04:46 UTC

**Comment by marcofranssen** [comment] 2020-07-01 18:59
I'm trying to use the MyCrypto desktop app on MacOS.

I'm using version `v1.7.11`.

It has the same issue, also when opening the advanced settings and clicking the refresh button of the nonce doesn't help.
