### ISSUE TITLE
Derivation paths not working for ETC

### ISSUE THREAD

**Issue by pyskell** [MyCryptoHQ/MyCrypto#2183] opened 2018-09-25 21:24 UTC
### Description of the Issue

I'm reporting this bug second hand so I can't provide too much detail but did witness this issue in person.

Go to send a transaction with a Ledger transaction on ETC's network and get a completely different from address than the unlocked wallet.

### Steps to Reproduce

1. Unlock Ledger wallet
1. Select proper address; shows balance
1. Go to send full balance to another address
1. Confirm on Ledger device
1. Confirmation screen on MyCrypto shows a different from address
1. Transaction fails to send

### Description of Your Machine

Chrome, Windows 7 or 10

**Comment by tayvano** [comment] 2018-09-26 22:01
Thats an interesting one. Will try to reproduce and fix ASAP

**Comment by Azarielle** [comment] 2018-09-27 17:51
[Added to Jira](https://mycrypto.atlassian.net/secure/RapidBoard.jspa?rapidView=19&projectKey=CORE&view=planning&selectedIssue=CORE-67)

**Comment by Azarielle** [comment] 2018-09-28 00:27
I require more information about this @pyskell : 
Could it be possible that you did not manually change the network to ETC before accessing the ETC derivation path on the pop up?

You can be on the ETH network but still select to open up Ledger ETC, but it won't work correctly.

**Comment by pyskell** [comment] 2018-10-01 13:07
To the best of my recollection it was connected to the ETC network as the correct wallet balance was being shown.

**Comment by tayvano** [comment] 2018-12-27 21:00
@pyskell We were never able to reproduce this. Have you seen it or heard of it occurring since your initial report?

**Comment by wtzb** [comment] 2020-01-21 13:21
Thank you for opening this issue. Since this issue applies to an older, no longer supported version of MyCrypto, I'm closing this to keep a better overview of issues that are currently applicable.

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!

**Closed by wtzb** 2020-01-21 13:21 UTC
Labels: type: triaging
