### ISSUE TITLE
Allow node selection from query parameter

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1484] opened 2018-04-09 20:03 UTC

**Comment by HenryNguyen5** [comment] 2018-04-09 20:06
Duplicate of #186?

**Comment by dternyak** [comment] 2018-04-09 20:10
Not quite, although they are similar.

I'm in the process of writing up a proper spec (that I'm about to implement), but this FR is much simpler. Instead of allowing new custom nodes to be added via query parameters as described in #186, this issue is simply to allow node selection of existing network via query parameters.

**Closed** 2018-04-12 23:17 UTC
Labels: high priority
