### ISSUE TITLE
Dollar symbol missing for CHF in Equivalent Values component

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/MyCrypto#1592] opened 2018-04-18 20:27 UTC
### Description of the Issue

When viewing a wallets equivalent values, the component is missing a symbol for CHF

### Console Logs / Screenshots

![image](https://user-images.githubusercontent.com/6404866/38956333-3d764514-4325-11e8-96db-4634cef89625.png)

**Comment by wbobeirne** [comment] 2018-04-18 22:08
This is working as intended, kind of. @james-prado discovered that the CHF _has no symbol_ beyond "CHF". I think we can close this one out, as eventually I'd like to make a setting for preferred currency and rework this view to only show that at some point.

**Comment by HenryNguyen5** [comment] 2018-04-18 22:10
![image](https://user-images.githubusercontent.com/6404866/38960731-b1781ff6-4333-11e8-81d8-9156169a8155.png)
They do have a symbol, its just that its literally `CHF`

**Comment by HenryNguyen5** [comment] 2018-04-18 22:14
Doh, i just repeated what you said, closing this

**Closed** 2018-04-18 22:14 UTC
Labels: S, ui
