### ISSUE TITLE
Assertion Failed When Wallet Holds WBTC

### ISSUE THREAD

**Issue by albasket** [MyCryptoHQ/MyCrypto#3912] opened 2021-03-31 17:11 UTC
### Description of Issue

Scanning for tokens at an address that holds WBTC results in a red error page with the message, "Assertion Failed."

### What exactly were you doing when you encountered this issue?

To reproduce:

1. Pick an address holding [WBTC](https://etherscan.io/token/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599). For example, the Uniswap V2 WBTC/USDC pool (0x004375dff511095cc5a197a54140a24efef3a416)
2. Open Desktop app and navigate to "View & Send"
3. Click "View Address," and use the address from step 1.
4. Click "Scan for Tokens"
5. Wait a few moments, then the red error page will pop up.

### How were you accessing your wallet?

Address, Private Key, or Mnemonic.

### Description of Your Machine

- Browser: N/A
- Browser version: N/A
- Operating system: Catalina
- Device: Macbook Pro
- MyCrypto.com vs Desktop Application? Desktop
- MyCrypto Version Number: 1.7.13 (1.7.13)

### Console Logs / Screenshots

...

**Comment by Mrtenz** [comment] 2021-03-31 21:29
Duplicate of #3890. The issue was fixed in #3900, which should be included in the next release (likely this week). You can use [app.mycrypto.com](https://app.mycrypto.com) as a workaround.

Thanks for the report!

**Closed by Mrtenz** 2021-03-31 21:29 UTC
