### ISSUE TITLE
cannot read property 'substr' of null

### ISSUE THREAD

**Issue by ksh** [MyCryptoHQ/MyCrypto#2450] opened 2019-03-23 17:05 UTC
If you're having an issue with unlocking your wallet, a transaction, a swap,
or an ENS auction, please email support@mycrypto.com. Github issues are for
development only, and support questions that aren't bugs or feature requests
will not be answered.

---

If you've experienced a bug, please provide the following information:

### Description of the Issue

I installed MyCrypto v1.6.1 on windows 10. Today and created a new Wallet

I could receive a small amount of ETH and one token OMG, but I cannot send ETH

### Steps to Reproduce

- open wallet
- select send Ether & Tokens
- Enter ETH amount 
- click on 'Send Transacion' button

 'Sign transaction's creen pops up, with two buttons 'Cancel' and 'Scan'. If I click on 'Cancel' or 'Scan', I receive following error message:

cannot read property 'substr' of null

There is no way that I can send out ETH

### Description of Your Machine

Chrome Version 72.0.3626.121 (Official Build) (64-bit), Windows 10, HP desktop

MyCrypto v1.6.1

### Console Logs / Screenshots

(Console logs or screenshots go here, if applicable)

---

If you're suggesting a feature, make sure someone hasn't already posted it. If
no one has, please provide the following information:

### Description of the Feature

(Your description goes here)

### Example(s) of Feature

(If another product or app is doing this, please link it)

**Comment by nickmccurdy** [comment] 2019-03-24 16:37
I can’t reproduce this in desktop 1.6.1 on mac, I only see cancel/send, not sign transaction or cancel/scan, then the transaction is successful

**Comment by nickmccurdy** [comment] 2019-03-24 16:46
What wallet type are you using? I was using keystore, it seems like you may be using Ledger or mnemonic.

**Comment by ksh** [comment] 2019-03-24 17:25
I had just created a wallet, with mnemonic, received ETH and got the error
when sending. Now I have exited MyCrypto, opened again and I was able to
send ETH. I don't have the error anymore.

Thank you,

**Comment by tayvano** [comment] 2019-03-25 15:54
Thanks for the detailed report @ksh. We'll keep our eyes peeled for others having the same issue and try to reproduce ourselves and reopen this issue if need be.

Seriously, your report was 💯. Feel free to let us know about anything else you experience.

**Comment by ksh** [comment] 2019-03-25 18:28
Hi,

I can reproduce the error.

- logout
- click 'View & Send' on menu
- click on 'Parity Signer'
- click on 'Use recent Account'
- select one account you have used

I'm directed to 'Send Ether & Tokens', screen where I enter 'To Address'
and 'Amount' . When I click on 'Send Transaction' I get the error I
reported before.

 I don't have the error if I sign in using mnemonic or keystore..

 ~ carlos

**Comment by blurpesec** [comment] 2019-03-26 17:40
Heya @ksh, which version of Parity Signer are you using?

**Comment by ksh** [comment] 2019-03-27 16:42
Hi, I can't find the version number for Parity Signer, but it was
downloaded two days ago from the Apple Store

 ~ carlos

**Comment by tayvano** [comment] 2019-03-30 09:14
It sounds like the address from the address book isn't passing to where it needs to be to generate the stuff for Parity sign transaction portion of the process.

**Comment by wtzb** [comment] 2020-01-27 09:30
Thank you for opening this issue. Since this issue applies to an older, no longer supported version of MyCrypto, I'm closing this to keep a better overview of issues that are currently applicable.

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!

**Closed by wtzb** 2020-01-27 09:30 UTC
