### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by babytasha85** [MyCryptoHQ/MyCrypto#3930] opened 2021-04-12 04:52 UTC
_Github issues are primarily for reporting bugs or getting assistance with development-related items. If you have a question or need support with our product, please email support@mycrypto.com for faster attention._

_If you are reporting an issue, please use the template below so we can reproduce, determine the cause of the issue, and fix it! If you are not reporting an issue, delete this entire thing and type away. Thanks!_

---

### Description of Issue

Got error msg "Assertion failed". with red screen.

### What exactly were you doing when you encountered this issue?
...I tried to change the network Eth to RSK and then view the balance.. and I got this error msg

...Give us some steps to reproduce...

### How were you accessing your wallet?

...Ledger, Trezor, MetaMask, Private Key, Keystore File, Mnemonic Phrase?...

### Description of Your Machine

- Browser: mac application
- Browser version:
- Operating system:
- Device:
- MyCrypto.com vs Desktop Application?
- MyCrypto Version Number:

### Console Logs / Screenshots

...

**Comment by Mrtenz** [comment] 2021-04-12 13:24
Duplicate of #3890. The issue was fixed in #3900, which should be included in the next release. You can use app.mycrypto.com as a workaround.

Thanks for the report!

**Closed by Mrtenz** 2021-04-12 13:24 UTC

**Comment by Domeonline888** [comment] 2021-04-12 23:21
Hi Mrtenz, unfortunatelly the app.mycrypto workaround doesn't work. I tested it for Apple and Windows.
Can i change the file  myself? Looks like the issue is just in line 258.
I have quite a few RIF tokens which are blocked now... 
Thanks,
Dominik

**Comment by Mrtenz** [comment] 2021-04-13 13:52
@Domeonline888 Does the same error occur on app.mycrypto.com? Can you provide a screenshot of that?

**Comment by Domeonline888** [comment] 2021-04-13 14:26
Thanks for picking this up Maarten,

Sure.
The first screen only stays for a few seconds. Took me a few times to capture it before it stays red:)





Thanks,
Dominik

**Comment by Mrtenz** [comment] 2021-04-13 14:30
@Domeonline888 Looks like your screenshot doesn't work on GitHub (I'm guessing because you're sending it via email). Can you send it to support@mycrypto.com directly? We'll get back to you through there. Thanks!
