### ISSUE TITLE
Network query parameter doesn't work

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#1601] opened 2018-04-18 21:24 UTC
### Description of the Issue

Adding `?network={desired network}` is supposed to connect you to said network, but I don't think it's working. Navigating to https://beta.mycrypto.com/account?network=etc for instance shows all the right visuals of trying to connect to the ETC network, but it will fail. Looking at the network requests, it looks as though it never actually pings any of the nodes. Hard to say if this is on the MyCrypto side, or the Shepherd side.

cc @dternyak @HenryNguyen5 

### Steps to Reproduce

1. Go to https://beta.mycrypto.com/account?network=etc
2. Fail to connect

**Comment by HenryNguyen5** [comment] 2018-04-18 21:35
Hm, https://beta.mycrypto.com/account?network=eth works, so it might be some type of race condition

**Comment by dternyak** [comment] 2018-04-18 21:42
Can confirm I am similarly not able to select any non-ethereum node via
network query parameter.

However, I pulled up the commit that was merged, and when testing on
MyCryptoBuilds, I am able to successfully switch networks.

https://mycryptobuilds.com/efa092cae125643013c9a9d14af3985f2de99a15/#/account?network=ETC

This leads me to believe that a recent change made in Shepherd is the cause
of the issue, as I don't remember any changes in the node logic on the app
side after this commit.

**Comment by wbobeirne** [comment] 2018-04-18 21:43
@HenryNguyen5 I'm pretty sure the issue is that whatever method it's using to switch to the new network, shepherd is always checking against ETH no matter what. So I think only `?network=eth` is working right now, but any other network won't.

**Closed** 2018-04-23 23:35 UTC
Labels: RC, issue
