### ISSUE TITLE
Messaging is returning "object Object" instead of "private key" when you attempt to unlock with your private key

### ISSUE THREAD

**Issue by tayvano** [MyCryptoHQ/MyCrypto#1667] opened 2018-04-24 23:08 UTC
Entering your `object Object` on a website is dangerous. If our website is compromised, or you accidentally visit a phishing website, you could lose your funds. Before you continue, consider

<img width="882" alt="2018-04-24 at 4 05 36 pm" src="https://user-images.githubusercontent.com/7924827/39218455-b40c70f0-47d9-11e8-942b-59995b266080.png">

**Comment by wbobeirne** [comment] 2018-04-24 23:10
Duplicate of #1569 which has been resolved in the latest `develop`

**Closed by wbobeirne** 2018-04-24 23:10 UTC
