### ISSUE TITLE
Contract encoding is wrong.

### ISSUE THREAD

**Issue by MicahZoltu** [MyCryptoHQ/MyCrypto#2433] opened 2019-03-15 08:19 UTC
### Description of the Issue

When I try to sign a transaction using MyCrypto, it is incorrectly encoding the transaction.

### Steps to Reproduce

1. Open MyCrypto and navigate to the Contracts view, and Interact tab.
1. Put in any address for the Contract Address
1. Fill in the ABI/JSON with:
    ```json
    [
        {
            "constant": false,
            "inputs": [
                {
                    "name": "tokenAddress",
                    "type": "address"
                },
                {
                    "name": "destination",
                    "type": "address"
                },
                {
                    "name": "amount",
                    "type": "uint256"
                }
            ],
            "name": "sendToken",
            "outputs": [],
            "payable": false,
            "type": "function",
            "stateMutability": "nonpayable"
        }
    ]
    ```
1. Click Access.
1. Choose `sendToken` method.
1. For the `tokenAddress` put in:
    `0xbaadf00dbaadf00dbaadf00dbaadf00dbaadf00d`
1. For the `destination` put in:
    `0xcafecafecafecafecafecafecafecafecafecafe`
1. For the `amount` put in:
    `1000000000000000000`
1. Fill in any gas price/limit/nonce and click Sign Transaction (I used a ledger).
1. Notice that the raw transaction's data is:
```
0x2fdcfbd20000000000000000000000000000002399f01ad62bc9263b07bb6db1084b9bb500000000000000000000000000000026b07bbbcae5a70c786557f0d75e658a2c0000000000000000000000000000000000000000000000000de0b6b3a7640000
```

### Description of Your Machine

Windows 10, MyCrypto desktop app, Ledger Nano.

### Console Logs / Screenshots

N/A

### Discussion

The signature is correctly being hashed as the first part of the data, however I expected to see some zeros followed by `baadf00d` repeated as the next 64 characters and some zeros followed by `cafe` repeated as the following 64 characters, finally ending with `0000000000000000000000000000000000000000000000000de0b6b3a7640000` (which is correct, 10**18 in hex).

I even deleted MyCrypto and re-installed the latest version, so I am pretty confident this isn't a caching issue (my "reinstall" mechanism completely blows away everything the MyCrypto installer and app has ever written to disk).

I tried entering the address with quotes, with and without the `0x` prefix, etc. but nothing seems to make them encode correctly.

**Comment by Mrtenz** [comment] 2019-03-16 09:41
I'm not able to reproduce this issue with a Ledger Nano S, MyCrypto version 1.6.1.

Following your steps, I get the following input data: `0x2fdcfbd2000000000000000000000000baadf00dbaadf00dbaadf00dbaadf00dbaadf00d000000000000000000000000cafecafecafecafecafecafecafecafecafecafe0000000000000000000000000000000000000000000000000de0b6b3a7640000`, which can be decoded as

```json
{
  "name": "sendToken",
  "types": [
    "address",
    "address",
    "uint256"
  ],
  "inputs": [
    "baadf00dbaadf00dbaadf00dbaadf00dbaadf00d",
    "cafecafecafecafecafecafecafecafecafecafe",
    "de0b6b3a7640000"
  ]
}
```

**Comment by MicahZoltu** [comment] 2019-03-16 09:47
After quitting and restarting the app a few times, I also became unable to reproduce the bug.  :cry:. I don't know what triggered it, or why it only happens sometimes, but it did happen, I swear!

**Comment by tayvano** [comment] 2019-04-05 10:00
I wonder if it's related to https://twitter.com/gakonst/status/1113024934329057280?s=19? 

Doesn't explain why it resolved itself tho. 🤔

**Comment by MicahZoltu** [comment] 2019-04-05 11:07
At a glance, that sounds unrelated as I was signing a contract call, not a message, and contract calls don't get any prefix.

**Comment by tayvano** [comment] 2019-04-10 20:17
So this may actually be related to some other weird reports re: ledgers

https://github.com/MyCryptoHQ/MyCrypto/issues/2485

What ledger firmware are you on @MicahZoltu

**Comment by MicahZoltu** [comment] 2019-04-16 12:12
It is an old Ledger, firmware 1.3.1.  ETH app 1.0.10.

**Comment by wtzb** [comment] 2020-01-27 11:14
Thank you so much for opening this issue. It appears that this issue is solved by updating your Ledger firmware to the latest version. Because of this, I'm closing this issue here. However, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us) if you think there might be more to this issue, so we can take a better look at it.

Thank you so much for reporting it! It's really appreciated.

**Closed by wtzb** 2020-01-27 11:14 UTC
Labels: cat: contracts, type: issue
