### ISSUE TITLE
MyCrypto desktop app on Arch unable to connect to Trezor One since v.1.7.2

### ISSUE THREAD

**Issue by guiand88** [MyCryptoHQ/MyCrypto#3492] opened 2020-09-05 02:47 UTC
### Description of Issue
Unable to connect to Trezor One wallet with the latest version 1.7.2
MyCypto.com is woking normally with Brave v.1.13.82 and with Librewolf v.80.0-2

### What exactly were you doing when you encountered this issue?

Updated from MyCrypto v.1.7.1 to v.1.7.2

### How were you accessing your wallet?

Trezor One, firmware 1.9.2
Updated to firmware 1.9.3 and the issue is still there

Issue occurs with both AppImage and the package from AUR.

### Description of Your Machine

- Operating system: Arch Linux
- Device: Trezor One
- MyCrypto Desktop Application
- MyCrypto Version Number: 1.7.2

### Console Logs / Screenshots
No output in the console
![mc](https://user-images.githubusercontent.com/9984546/92296226-dbdeea80-ef21-11ea-8b69-aaed007b0461.jpg)

**Comment by Mrtenz** [comment] 2020-09-05 10:03
Thank you for letting us know. There was a regression bug caused by a recent update, but this should be fixed in #3485, which is scheduled to be released soon. In the meantime you can use the web app, or use an older version of the desktop app.

**Closed by Mrtenz** 2020-09-05 10:03 UTC
