### ISSUE TITLE
Open / Close disclaimer is always bound to esc

### ISSUE THREAD

**Issue by james-prado** [MyCryptoHQ/MyCrypto#1152] opened 2018-02-20 22:29 UTC
### Description of the Issue

Pressing esc anywhere on the site will open the disclaimer. Instead esc should only close the disclaimer, not toggle it.

### Steps to Reproduce

press esc

**Comment by wbobeirne** [comment] 2018-02-20 22:49
Duplicate of #1097.

**Closed by wbobeirne** 2018-02-20 22:49 UTC
Labels: issue: low
