### ISSUE TITLE
Bad ENS names are shown as valid 

### ISSUE THREAD

**Issue by Azarielle** [MyCryptoHQ/MyCrypto#1921] opened 2018-06-08 17:32 UTC
![image](https://user-images.githubusercontent.com/25834495/41171965-4c98dc64-6b20-11e8-94a1-7d66a4e2543b.png)

**Comment by Azarielle** [comment] 2018-06-08 17:32
#1889

**Comment by dternyak** [comment] 2018-06-08 17:34
Duplicate of #1889

**Closed by dternyak** 2018-06-08 17:34 UTC
Labels: issue
